version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - SOURCE_BUCKET=your-source-bucket-name
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
    volumes:
      - ./credentials.json:/app/credentials.json:ro
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://localhost:8000
    depends_on:
      - backend
    restart: unless-stopped 